setup_tasks:
 - apt-get update && apt-get install libgit2-0 libgit2-dev

tasks:
 - tox -e flake8
 - tox -e isort
 - tox -e tests
 - coverage report && coverage xml

coverage:
 parser: python
 path: coverage.xml
